name: Enforce PR Size

jobs:
  check_pr_size:
    name: Check PR size doesn't break set limit
    runs-on: ubuntu-latest
    steps:
      - uses: neralake/.github/actions/pr-size-check@main
        with:
          max_lines_changed: 1000
